version: "3.9"

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    network_mode: host
    # ports:
    #   - "80:80"
    #   - "81:81"   # UI quản trị
    #   - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
