version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis_rdb
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./data:/data                                  # nơi lưu dump.rdb
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro   # cấu hình RDB

volumes:
  redis_data:
